In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

# File to Load (Remember to Change These)
school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

# Read School and Student Data File and store into Pandas Data Frames
school_data = pd.read_csv(school_data_to_load)
student_data = pd.read_csv(student_data_to_load)

# Combine the data into a single dataset
school_data_complete = pd.merge(school_data, student_data, how="inner", on=["school_name"])

In [2]:
# Calculate the budget total under school_data
budget_total = school_data["budget"].sum()

# Calculate the total schools under school_data
total_schools = len(school_data["school_name"].unique())

# Calculate the total number of Students under student_data_complete
grouped = school_data_complete.groupby("school_name")["budget"].apply(lambda x: x.count())
students = grouped.sum()

# Calculate the Average Math score under student_data
avg_math = student_data["math_score"].mean()

# Calculate the Average Reading score under student_data
avg_reading = student_data["reading_score"].mean()

# Calculate the Overall passing score with calculated scores
overall_passing = (avg_reading + avg_math)/2

# Create a Dataframe with a summary
district_summary_table = pd.DataFrame({
    "Total Schools": [total_schools],
    "Total Students": [students],
    "Total Budget": [budget_total],
    "Average Math Score": [avg_math],
    "Average Reading Score": [avg_reading],
    "Overall Passing Rate": [overall_passing]
    })

district_summary_table

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,Overall Passing Rate
0,15,39170,24649428,78.985371,81.87784,80.431606

In [3]:
top_per_group = school_data_complete.groupby("school_name")

top_per = top_per_group.agg({
    "type": "unique",
    "budget": "sum",
    "student_name": "count",
    "math_score": "mean",
    "reading_score": "mean" })

top_per["passing_reading_pct"] = top_per_group.apply(lambda x: (x["reading_score"] >= 70).sum() / x["student_name"].count()) * 100
top_per["passing_math_pct"] = top_per_group.apply(lambda x: (x["math_score"] >= 70).sum() / x["student_name"].count()) * 100

top_per["Overall Passing Rate"] = (top_per["passing_reading_pct"] + top_per["passing_math_pct"])/2
top_per
result_top = top_per.sort_values(by='Overall Passing Rate', ascending=False, na_position='first')

result_top.head()

,type,budget,student_name,math_score,reading_score,passing_reading_pct,passing_math_pct,Overall Passing Rate
school_name,,,,,,,,
Cabrera High School,[Charter],2009159448,1858,83.061895,83.975780,97.039828,94.133477,95.586652
Thomas High School,[Charter],1705517550,1635,83.418349,83.848930,97.308869,93.272171,95.290520
Pena High School,[Charter],563595396,962,83.839917,84.044699,95.945946,94.594595,95.270270
Griffin High School,[Charter],1346890000,1468,83.351499,83.816757,97.138965,93.392371,95.265668
Wilson High School,[Charter],3012587442,2283,83.274201,83.989488,96.539641,93.867718,95.203679

In [4]:
result_bottom = top_per.sort_values(by='Overall Passing Rate', ascending=True, na_position='last')
result_bottom.head()

,type,budget,student_name,math_score,reading_score,passing_reading_pct,passing_math_pct,Overall Passing Rate
school_name,,,,,,,,
Rodriguez High School,[District],10186904637,3999,76.842711,80.744686,80.220055,66.366592,73.293323
Figueroa High School,[District],5557128039,2949,76.711767,81.158020,80.739234,65.988471,73.363852
Huang High School,[District],5573322295,2917,76.629414,81.182722,81.316421,65.683922,73.500171
Johnson High School,[District],14733628650,4761,77.072464,80.966394,81.222432,66.057551,73.639992
Ford High School,[District],4831365924,2739,77.102592,80.746258,79.299014,68.309602,73.804308

In [5]:
ninth = school_data_complete.groupby(school[(school_data_complete["grade"]=="9th")]
tenth = school_data_complete[(school_data_complete["grade"]=="10th")]
eleventh = school_data_complete[(school_data_complete["grade"]=="11th")]
twelfth = school_data_complete[(school_data_complete["grade"]=="12th")]
school_name = school_data_complete["school_name"]

math_scores = pd.DataFrame({
    "School Name": [school_name],
    "9th": [ninth],
    "10th": [tenth],
    "11th": [eleventh],
    "12th": [twelfth]
    })
math_scores =  school_data_complete.groupby([school_data_comple["math_score"].mean()
math_scores = school_data_complete.reset_index().groupby(["school_name"])["grade"].aggregate('first').unstack()

math_scores

SyntaxError: invalid syntax (<ipython-input-5-2f2ce8ab8b6a>, line 2)

In [6]:
ninth = school_data_complete[(school_data_complete["grade"]=="9th")]
tenth = school_data_complete[(school_data_complete["grade"]=="10th")]
eleventh = school_data_complete[(school_data_complete["grade"]=="11th")]
twelfth = school_data_complete[(school_data_complete["grade"]=="12th")]
school_name = school_data_complete["school_name"]

math_scores = pd.DataFrame({
    "School Name": [school_name],
    "9th": [ninth],
    "10th": [tenth],
    "11th": [eleventh],
    "12th": [twelfth]
    })
reading_scores =  school_data_complete.groupby([school_data_comple["reading_score"].mean()
reading_scores = school_data_complete.reset_index().groupby(["school_name"])["grade"].aggregate('first').unstack()

reading_scores

SyntaxError: invalid syntax (<ipython-input-6-65bc0a12f197>, line 15)

In [7]:
spending_bins = [0, 585, 615, 645, 675]
group_names = ["<$585", "$585-615", "$615-645", "$645-675"]
scores_spending = school_data_complete.groupby("group_names")

scores_spending = top_per.agg({
    "math_score": "mean",
    "reading_score": "mean",
    "passing_math_pct": "count",
    "passing_reading": "count",
    "Overall Passing Rate": "count" })

scores_spending

KeyError: 'group_names'

In [8]:
size_bins = [0, 1000, 2000, 5000]
group_names = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]
scores_size = school_data_complete.groupby("group_names")

scores_size = top_per.agg({
    "math_score": "mean",
    "reading_score": "mean",
    "passing_math_pct": "count",
    "passing_reading": "count",
    "Overall Passing Rate": "count" })

scores_size

KeyError: 'group_names'

In [9]:
scores_spending = school_data_complete.groupby("type")

scores_type = scores_spending.agg({
    "math_score": "mean",
    "reading_score": "mean",
    "passing_math_pct": "count",
    "passing_reading": "count",
    "Overall Passing Rate": "count" })

scores_type.head()

/Users/layla/anaconda3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py:4656: FutureWarning: using a dict with renaming is deprecated and will be removed in a future version
  return super(DataFrameGroupBy, self).aggregate(arg, *args, **kwargs)

KeyError: 'passing_math_pct'